src/RestOfUs.Web/Models/AuthorizeScopesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RestOfUs.Common.Entities.OAuth2;

namespace RestOfUs.Web.Models {
    public class AuthorizeScopesViewModel {
        public string ClientAppName { get; set; }
        public string Username { get; set; }
        public IEnumerable<string> Scopes { get; set; }
        public string RedirectUri { get; set; }
        public string State { get; set; }
        public string ClientId { get; set; }
    }

    public class RedirectViewModel {
        public ClientApplication Client { get; set; }
        public ClientAuthorization Authorization { get; set; }
        public Uri RedirectUri { get; set; }
    }
}

src/RestOfUs.Web/Models/SignInViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RestOfUs.Web.Models {
    public class SignInViewModel {
        public string Message { get; set; }
        public string ReturnUrl { get; set; }
    }
}

src/RestOfUs.Web/Controllers/AccountController.cs
using System.Web.Mvc;
using RestOfUs.Common.Services;
using RestOfUs.Services;
using RestOfUs.Web.Models;
using RestOfUs.Web.Services;

namespace RestOfUs.Web.Controllers {
    [Authorize]
    public class AccountController : Controller {

        private readonly IUserStore userStore;
        private readonly IAuthenticator authenticator;

        public AccountController(IUserStore userStore, IAuthenticator authenticator) {
            this.userStore = userStore;
            this.authenticator = authenticator;
        }

        [AllowAnonymous]
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult SignIn(string returnUrl, string message) {
            message = message ?? "Please sign in";
            var model = new SignInViewModel {
                Message = message,
                ReturnUrl = returnUrl
            };
            return (View(model));
        }

        public ActionResult SignOut() {
            authenticator.SignOut();
            return (RedirectToAction("Index", "Home"));
        }

        [AllowAnonymous]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult SignIn(string username, string password, string returnUrl, bool remember = false) {
            var user = userStore.FindUserByUsername(username);
            if (user == null) return (SignIn(returnUrl, "Username not found"));
            if (user.PasswordMatches(password)) {
                authenticator.SetAuthCookie(username, remember);
                var url = returnUrl ?? Url.Action("Index", "Account");
                return (Redirect(url));
            }
            return (SignIn(returnUrl, "Incorrect password"));
        }

        public ActionResult Index() {
            return (View(User));
        }
    }
}

src/RestOfUs.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace RestOfUs.Web.Controllers {
    public class HomeController : Controller {
        public ActionResult Index() {
            return View();
        }
    }
}

src/RestOfUs.Web/Controllers/OAuth2Controller.cs
using System;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RestOfUs.Common.Entities.OAuth2;
using RestOfUs.Common.Services;
using RestOfUs.Web.Models;
using RestOfUs.Web.OAuth2;

// ReSharper disable InconsistentNaming
namespace RestOfUs.Web.Controllers {
    [Authorize]
    public class OAuth2Controller : Controller {
        private readonly IOAuth2DataStore oAuth2DataStore;

        public OAuth2Controller(IOAuth2DataStore oAuth2DataStore) {
            this.oAuth2DataStore = oAuth2DataStore;
        }

        public ActionResult Authorize(
            string response_type, string client_id, string redirect_uri, string state,
            string scope) {
            var client = oAuth2DataStore.FindClient(client_id);
            if (client == null) throw (new HttpException((int)HttpStatusCode.BadRequest, "Invalid client_id"));
            var scopes = scope.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
            var model = new AuthorizeScopesViewModel {
                ClientId = client_id,
                RedirectUri = redirect_uri,
                State = state,
                ClientAppName = client.Name,
                Username = User.Identity.Name,
                Scopes = scopes
            };
            return (View(model));
        }

        public ActionResult Token(string grant_type, string code, string redirect_uri, string refresh_token) {
            switch (grant_type) {
                case "authorization_code":
                    return (CreateTokens(code, redirect_uri));
                case "refresh_token":
                    return (RefreshToken(refresh_token));
                default:
                    throw (BadRequest("unsupported grant_type"));
            }
        }

        private ActionResult RefreshToken(string refreshToken) {
            throw new NotImplementedException();
        }

        private ActionResult CreateTokens(string code, string redirectUri) {
            var authorization = oAuth2DataStore.FindAuthorization(code);
            if (authorization == null) throw (BadRequest("invalid authorization code"));
            if (authorization.Expired) throw (BadRequest("authorization no longer valid"));
            var refreshToken = authorization.CreateRefreshToken();
            
        }

        public ActionResult Redirect(string response_type, string client_id, string redirect_uri, string state,
            string scope) {
            var scopes = scope.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
            var client = oAuth2DataStore.FindClient(client_id);
            if (client == null) throw (new HttpException((int)HttpStatusCode.BadRequest, "Invalid client_id"));
            var auth = new ClientAuthorization(client_id, User.Identity.Name, redirect_uri, scopes);
            oAuth2DataStore.SaveAuthorization(auth);
            var query = HttpUtility.ParseQueryString(String.Empty);
            query["code"] = auth.Code;
            query["state"] = state;
            var uri = new UriBuilder(redirect_uri) {
                Query = query.ToString()
            };
            var model = new RedirectViewModel() {
                RedirectUri = uri.Uri,
                Client = client,
                Authorization = auth
            };
            return (View(model));
        }

        private HttpException BadRequest(string message) {
            return (new HttpException((int)HttpStatusCode.BadRequest, message));
        }
    }
}
// ReSharper restore InconsistentNaming

src/RestOfUs.Web/Views/Home/Index.cshtml
@model dynamic

@{
}
<h1>welcome to restofus</h1>
<p>A simple application that demonstrates OAuth2 authentication.</p>
<p>please <a href="@Url.Action("signin", "account")">sign in</a> to get started</p>

src/RestOfUs.Web/Views/OAuth2/Authorize.cshtml
@using RestOfUs.Web.OAuth2
@model RestOfUs.Web.Models.AuthorizeScopesViewModel

@{
    ViewBag.Title = "Authorize a Thing!";
}


<form action="@Url.Action("Redirect", "OAuth2")" method="POST">
    <h1>hello, @Model.Username</h1>
    <h2>@Model.ClientAppName would like to:</h2>
    <ul>
        @foreach (var scope in Model.Scopes) {
            <li>@Scope.Describe(scope)</li>
        }
    </ul>
    <input type="hidden" name="redirect_uri" value="@Model.RedirectUri" />
    <input type="hidden" name="scope" value="@String.Join(" ", Model.Scopes)" />
    <input type="hidden" name="client_id" value="@Model.ClientId" />
    <input type="hidden" name="state" value="@Model.State" />
    <input type="submit" value="I'm OK with this!" />
</form>

src/RestOfUs.Web/Views/OAuth2/Redirect.cshtml
@using RestOfUs.Web.OAuth2
@model RestOfUs.Web.Models.RedirectViewModel

@{
    ViewBag.Title = "title";
}
<h2>Redirecting you back to the client application</h2>
<p>Here's what's happened so far:</p>
<ol>
    <li>
        <strong>@Model.Client.Name</strong> has requested access to:
        <ul>
            @foreach (var scope in Model.Authorization.Scope) {
                <li>@Scope.Describe(scope)</li>
            }
        </ul>
    </li>
    <li>You've told us you're happy with this.</li>
    <li>We've recorded your authorization using the unique code @Model.Authorization.Code</li>
</ol>
<p>Now, we're redirecting you back to the <code>redirect_uri</code> supplied by <strong>@Model.Client.Name</strong>, and including this code in the redirect URI.</p>
<p>
    <strong>@Model.Client.Name</strong> will then make a request back to the RestOfUs server and exchange this code for an <strong>access token</strong>
    and a <strong>refresh token</strong>
</p>
<p>Once that's all clear, go here to continue:</p>
<p><a href="@Model.RedirectUri.AbsoluteUri">@Model.RedirectUri.AbsoluteUri</a></p>

src/RestOfUs.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>RestOfUs</title>
    <link type="text/css" rel="stylesheet" href="@Url.Content("~/Content/Styles/styles.css")" />
</head>
<body>
    <header>
        @if (User.Identity.IsAuthenticated) {
            @User.Identity.Name
            <text>&bull;</text>
            <a href="@Url.Action("index", "account")">my account</a>
            <text>&bull;</text>
            <a href="@Url.Action("signout", "account")">sign out</a>
        } else {
            <a href="@Url.Action("signin", "account")">sign in</a>
        }

    </header>
    <section>
        @RenderBody()
    </section>
    <footer>
        restofus &bull; a ReST demo application by @@dylanbeattie &bull; <a href="http://www.github.com/dylanbeattie/restofus">http://www.github.com/dylanbeattie/restofus</a>

    </footer>
</body>
</html>